### ISSUE TITLE
Needs Makefile or way to build dependent binaries

### ISSUE THREAD

**Issue by bunnie** [chibitronics/jig-20-config-ltc#1]
gpiopoll, pi-blaster, measure-reset needs building and it's not obvious anywhere that these need building. 

Maybe add a Makefile and a note in the README that this needs to happen for the repo to work?

**Comment by xobs** [comment]
Closed by 54bc318c24c2de44f003a8080cb33902aa67b1a5 and 3e8db86df3c8091422a7c3f407af87531450506c
